"""baseline: existing schema

Revision ID: 105c8b1f82fa
Revises: 
Create Date: 2026-07-18 17:44:41.385232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105c8b1f82fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_info_name'), ['name'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('salary_raw', sa.String(length=200), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('remote_ok', sa.Boolean(), nullable=True),
    sa.Column('language_required', sa.String(length=50), nullable=True),
    sa.Column('skills_extracted', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'SHORTLISTED', 'VIEWED', 'CONSIDERING', 'APPLIED', 'REJECTED', 'INTERVIEWING', 'OFFER', 'ARCHIVED', name='jobstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('user_stars', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('source_job_id', sa.String(length=300), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_dedup_hash'), ['dedup_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_score', ['status', 'match_score'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cover_letter_language', sa.String(length=10), nullable=True),
    sa.Column('apply_method', sa.String(length=50), nullable=True),
    sa.Column('recipient_email', sa.String(length=300), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'ACKNOWLEDGED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('VIEWED', 'APPLIED', 'CONFIRMATION', 'RECRUITER_CALL', 'INTERVIEW_1', 'INTERVIEW_2', 'TECHNICAL', 'OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'REJECTED', 'NOTE', name='applicationevent'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('raw_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_job_id', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_raw_source_id')
    )
    with op.batch_alter_table('raw_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_jobs_canonical_id'), ['canonical_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_jobs_canonical_id'))

    op.drop_table('raw_jobs')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_score')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_direction'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedup_hash'))

    op.drop_table('jobs')
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_info_name'))

    op.drop_table('company_info')
    # ### end Alembic commands ###
