"""add resume_versions, interviews, interview_questions, star_stories

Revision ID: b849cb13662f
Revises: 105c8b1f82fa
Create Date: 2026-07-18 17:49:35.740613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b849cb13662f'
down_revision: Union[str, Sequence[str], None] = '105c8b1f82fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direction', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_format', sa.Enum('PDF', 'DOCX', 'TXT', name='fileformat'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index('ix_resume_versions_direction_active', ['direction', 'is_active'], unique=False)

    op.create_table('star_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.Enum('PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'ONSITE', 'FINAL', 'OTHER', name='interviewtype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('interviewer_name', sa.String(length=200), nullable=True),
    sa.Column('format', sa.Enum('VIDEO', 'PHONE', 'ONSITE', name='interviewformat'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'PASSED', 'FAILED', 'CANCELLED', name='interviewoutcome'), nullable=False),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('went_well', sa.Text(), nullable=True),
    sa.Column('to_improve', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('my_answer', sa.Text(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('optimized_answer', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_interview_id'), ['interview_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_applications_resume_version_id_resume_versions',
            'resume_versions', ['resume_version_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_resume_version_id_resume_versions', type_='foreignkey')
        batch_op.drop_column('resume_version_id')

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_interview_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_interviews_job_id'))

    op.drop_table('interviews')
    op.drop_table('star_stories')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_resume_versions_direction_active')

    op.drop_table('resume_versions')
    # ### end Alembic commands ###
